//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KLance.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public System.DateTime StartDate { get; set; }
        public int DurationOfProject { get; set; }
        public decimal FixedPrice { get; set; }
        public System.DateTime PostedDate { get; set; }
        public bool Status { get; set; }
        public System.DateTime BidStartDate { get; set; }
        public System.DateTime BidEndDate { get; set; }
        public int EmployerID { get; set; }
    
        public virtual Employer Employer { get; set; }
    }
}
